[package]
name = "vodozemac-js"
version = "0.1.0"
edition = "2024"

[lib]
name = "vodozemac"
crate-type = ["cdylib"]

[dependencies]
vodozemac = { path = "..", features = ["libolm-compat", "js"] }
wasm-bindgen = "0.2.80"
js-sys = "0.3.57"
serde-wasm-bindgen = "0.4.2"